/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/MarsGallery.glb')
  return (
    <group ref={group} {...props} dispose={null} position={[-26,2,20]} rotation={[0,3.14*(1/2),0]}>
      <mesh
        geometry={nodes.Landscape003.geometry}
        material={materials.ground}
        position={[-3.75, -0.82, -0.26]}
        rotation={[-Math.PI, 1.56, -Math.PI]}
        scale={[8.07, 8.07, 8.07]}
      />
      <mesh
        geometry={nodes.amonggus.geometry}
        material={materials.cyan}
        position={[-9.41, 0.4, 5.18]}
        rotation={[Math.PI, -1.49, Math.PI]}
        scale={[0.62, 0.62, 0.62]}>
        <mesh geometry={nodes.Cylinder048_1.geometry} material={materials['Material.001']} position={[0.91, 0, 0]} />
      </mesh>
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={nodes.Icosphere.material}
        position={[-8.46, -0.58, 2.62]}
        scale={[0.49, 0.54, 0.52]}
      />
      <mesh
        geometry={nodes.Icosphere001.geometry}
        material={nodes.Icosphere001.material}
        position={[-9.16, -0.71, 2.53]}
        scale={[0.29, 0.3, 0.34]}
      />
      <mesh
        geometry={nodes.Icosphere002.geometry}
        material={nodes.Icosphere002.material}
        position={[-10.48, -0.97, 5.06]}
        scale={[0.15, 0.15, 0.2]}
      />
      <mesh
        geometry={nodes.Icosphere003.geometry}
        material={nodes.Icosphere003.material}
        position={[-10.55, -1.01, 5.27]}
        scale={[0.05, 0.05, 0.06]}
      />
      <mesh
        geometry={nodes.Icosphere004.geometry}
        material={nodes.Icosphere004.material}
        position={[-10.33, -1.09, 5.31]}
        rotation={[0.53, 0, 0]}
        scale={[0.1, 0.1, 0.14]}
      />
      <mesh
        geometry={nodes.Icosphere005.geometry}
        material={nodes.Icosphere005.material}
        position={[-2.1, -0.54, 5.32]}
        rotation={[-0.26, -0.3, -0.45]}
        scale={[0.56, 0.32, 0.46]}
      />
      <mesh
        geometry={nodes.Icosphere006.geometry}
        material={nodes.Icosphere006.material}
        position={[-1.76, -0.86, 6]}
        rotation={[-1.15, -0.26, -1.62]}
        scale={[0.24, 0.14, 0.2]}
      />
      <mesh
        geometry={nodes.Icosphere007.geometry}
        material={nodes.Icosphere007.material}
        position={[3.19, -0.8, 2.13]}
        scale={[0.36, 0.21, 0.29]}
      />
      <mesh
        geometry={nodes.Icosphere008.geometry}
        material={nodes.Icosphere008.material}
        position={[2.8, -0.84, 2.56]}
        scale={[0.36, 0.21, 0.29]}
      />
      <mesh
        geometry={nodes.Icosphere009.geometry}
        material={nodes.Icosphere009.material}
        position={[3.19, -1.22, 4.09]}
        scale={[0.2, 0.11, 0.22]}
      />
      <mesh
        geometry={nodes.Icosphere010.geometry}
        material={nodes.Icosphere010.material}
        position={[3.24, -1.24, 4.36]}
        scale={[0.09, 0.05, 0.07]}
      />
      <mesh
        geometry={nodes.Icosphere011.geometry}
        material={nodes.Icosphere011.material}
        position={[3.3, -0.75, 2.69]}
        rotation={[0, 0, -1.13]}
        scale={[0.11, 0.06, 0.09]}
      />
      <mesh
        geometry={nodes.Icosphere012.geometry}
        material={nodes.Icosphere012.material}
        position={[2.34, -1.19, -4.96]}
        rotation={[0.42, 0, -0.34]}
        scale={[0.61, 0.18, 0.51]}
      />
      <mesh
        geometry={nodes.Icosphere013.geometry}
        material={nodes.Icosphere013.material}
        position={[3.05, -1.3, -4.85]}
        rotation={[0.42, 0, -0.34]}
        scale={[0.27, 0.08, 0.22]}
      />
      <mesh
        geometry={nodes.Icosphere014.geometry}
        material={nodes.Icosphere014.material}
        position={[-3.75, -0.58, -2.94]}
        scale={[0.59, 0.41, 0.42]}
      />
      <mesh
        geometry={nodes.Icosphere015.geometry}
        material={nodes.Icosphere015.material}
        position={[-3.77, -0.76, -2.32]}
        scale={[0.33, 0.22, 0.18]}
      />
      <mesh
        geometry={nodes.Icosphere016.geometry}
        material={nodes.Icosphere016.material}
        position={[-2.99, -0.74, -3.1]}
        scale={[0.24, 0.17, 0.17]}
      />
      <mesh
        geometry={nodes.Icosphere017.geometry}
        material={nodes.Icosphere017.material}
        position={[-3.57, -0.87, 1.49]}
        scale={[0.36, 0.4, 0.31]}
      />
      <mesh
        geometry={nodes.Icosphere018.geometry}
        material={nodes.Icosphere018.material}
        position={[-7.31, 0.26, -5.51]}
        rotation={[0.2, -0.2, 0.55]}
        scale={[0.53, 0.76, 0.42]}
      />
      <mesh
        geometry={nodes.Icosphere019.geometry}
        material={nodes.Icosphere019.material}
        position={[-8.06, 0.54, -5.24]}
        rotation={[-0.39, -0.9, -1.52]}
        scale={[0.39, 0.56, 0.31]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0, 0.37, 0]}
        scale={[1.15, 0.35, 1.77]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[-0.58, 1.21, 1.2]}
        scale={[0.14, 0.48, 0.14]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-0.57, 1.9, 1.15]}
        scale={[0.49, 0.19, 0.49]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[0, 1.07, -1.04]}
        rotation={[0.42, 0, 0]}
        scale={[0.74, 0.27, 0.79]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[1.28, 0.38, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.11, 0.15, 0.11]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[1.33, -0.08, 0.72]}
        rotation={[1.99, 0, 0]}
        scale={[0.09, 0.76, 0.09]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[1.33, 0.01, -0.76]}
        rotation={[-2.15, 0, 0]}
        scale={[0.09, 0.76, 0.09]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        position={[1.41, 0.05, -0.66]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.11, 0.22, 0.11]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[1.52, -0.34, -1.46]}
        rotation={[-2.15, 0, 0]}
        scale={[0.09, 0.76, 0.09]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
        position={[1.52, -0.53, 0.03]}
        rotation={[2.13, 0, 0]}
        scale={[0.09, 0.76, 0.09]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={nodes.Cylinder015.material}
        position={[1.74, -0.38, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[-0.12, -0.57, -0.12]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={nodes.Cylinder016.material}
        position={[2.07, -0.38, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.44, 0.25, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={nodes.Cylinder018.material}
        position={[2.22, -0.38, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.07, 0.05, 0.07]}
      />
      <mesh
        geometry={nodes.Cylinder019.geometry}
        material={nodes.Cylinder019.material}
        position={[1.74, -0.38, -1.32]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[-0.12, -0.57, -0.12]}
      />
      <mesh
        geometry={nodes.Cylinder020.geometry}
        material={nodes.Cylinder020.material}
        position={[2.07, -0.38, -1.32]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.44, 0.25, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={nodes.Cylinder022.material}
        position={[2.22, -0.38, -1.32]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.07, 0.05, 0.07]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials['Material.006']}
        position={[-0.57, 1.9, 1.15]}
        scale={[0.49, 0.19, 0.49]}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={nodes.Cylinder023.material}
        position={[-0.39, 1.91, 1.66]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.11, 0.02, 0.11]}
      />
      <mesh
        geometry={nodes.Cylinder024.geometry}
        material={nodes.Cylinder024.material}
        position={[0.6, 0.89, 0.39]}
        scale={[0.16, 0.16, 0.16]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[0, 0.26, 1.63]}
        scale={[0.76, 0.27, 0.27]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[1.02, 0.27, 0]}
        scale={[0.11, 0.24, 0.78]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[0, 0.86, -0.28]}
        rotation={[0.42, 0, 0]}
        scale={[0.49, 0.3, 0.39]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[1.06, 0.76, -1.65]}
        scale={[0.19, 0.26, 0.19]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[0.26, 1.5, -1.21]}
        rotation={[0.42, 0, 0]}
        scale={[0.24, 0.25, 0.24]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[0, 0.11, 0]}
        scale={[1.19, 0.24, 2.61]}
      />
      <mesh
        geometry={nodes.Cylinder025.geometry}
        material={nodes.Cylinder025.material}
        position={[-1.3, 0.38, 0.29]}
        rotation={[Math.PI / 2, 0, 1.55]}
        scale={[0.11, 0.15, 0.11]}
      />
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={nodes.Cylinder026.material}
        position={[-1.37, -0.08, -0.44]}
        rotation={[1.15, 0.01, 3.12]}
        scale={[0.09, 0.76, 0.09]}
      />
      <mesh
        geometry={nodes.Cylinder027.geometry}
        material={nodes.Cylinder027.material}
        position={[-1.33, 0.01, 1.05]}
        rotation={[-0.99, 0.01, -3.12]}
        scale={[0.09, 0.76, 0.09]}
      />
      <mesh
        geometry={nodes.Cylinder028.geometry}
        material={nodes.Cylinder028.material}
        position={[-1.41, 0.05, 0.95]}
        rotation={[Math.PI / 2, 0, 1.55]}
        scale={[0.11, 0.22, 0.11]}
      />
      <mesh
        geometry={nodes.Cylinder029.geometry}
        material={nodes.Cylinder029.material}
        position={[-1.5, -0.34, 1.76]}
        rotation={[-0.99, 0.01, -3.12]}
        scale={[0.09, 0.76, 0.09]}
      />
      <mesh
        geometry={nodes.Cylinder030.geometry}
        material={nodes.Cylinder030.material}
        position={[-1.53, -0.53, 0.26]}
        rotation={[1.02, 0.01, 3.12]}
        scale={[0.09, 0.76, 0.09]}
      />
      <mesh
        geometry={nodes.Cylinder039.geometry}
        material={nodes.Cylinder039.material}
        position={[-1.76, -0.38, 0.3]}
        rotation={[Math.PI / 2, 0, 1.55]}
        scale={[-0.12, -0.57, -0.12]}
      />
      <mesh
        geometry={nodes.Cylinder040.geometry}
        material={nodes.Cylinder040.material}
        position={[-2.09, -0.38, 0.3]}
        rotation={[Math.PI / 2, 0, 1.55]}
        scale={[0.44, 0.25, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder042.geometry}
        material={nodes.Cylinder042.material}
        position={[-2.24, -0.38, 0.31]}
        rotation={[Math.PI / 2, 0, 1.55]}
        scale={[0.07, 0.05, 0.07]}
      />
      <mesh
        geometry={nodes.Cylinder043.geometry}
        material={nodes.Cylinder043.material}
        position={[-1.73, -0.38, 1.62]}
        rotation={[Math.PI / 2, 0, 1.55]}
        scale={[-0.12, -0.57, -0.12]}
      />
      <mesh
        geometry={nodes.Cylinder044.geometry}
        material={nodes.Cylinder044.material}
        position={[-2.06, -0.38, 1.62]}
        rotation={[Math.PI / 2, 0, 1.55]}
        scale={[0.44, 0.25, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder046.geometry}
        material={nodes.Cylinder046.material}
        position={[-2.21, -0.38, 1.63]}
        rotation={[Math.PI / 2, 0, 1.55]}
        scale={[0.07, 0.05, 0.07]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials['Material.008']}
        position={[0.54, 0.67, 1.66]}
        scale={[0.16, 0.09, 0.11]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[-0.29, 1.97, 1.16]}
        scale={[0.21, 0.16, 0.29]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[2.07, -0.38, 1.34]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.44, 0.25, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={nodes.Cylinder013.material}
        position={[2.08, -0.38, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.44, 0.25, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={nodes.Cylinder017.material}
        position={[2.07, -0.38, -1.32]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.44, 0.25, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={nodes.Cylinder021.material}
        position={[-2.12, -0.38, -1.03]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.44, 0.25, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder033.geometry}
        material={nodes.Cylinder033.material}
        position={[-2.09, -0.38, 0.3]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.44, 0.25, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder037.geometry}
        material={nodes.Cylinder037.material}
        position={[-2.06, -0.38, 1.62]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.44, 0.25, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder041.geometry}
        material={materials['Material.005']}
        position={[-0.39, 1.91, 1.68]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.1, 0.02, 0.1]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[1.7, -0.38, 1.34]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[-0.12, -0.57, -0.12]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        position={[2.07, -0.38, 1.34]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.44, 0.25, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
        position={[2.07, -0.38, 1.34]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.07, 0.05, 0.07]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={nodes.Cylinder012.material}
        position={[-1.78, -0.38, -1.03]}
        rotation={[Math.PI / 2, 0, 1.55]}
        scale={[-0.12, -0.57, -0.12]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={nodes.Cylinder014.material}
        position={[-2.12, -0.38, -1.03]}
        rotation={[Math.PI / 2, 0, 1.55]}
        scale={[0.44, 0.25, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder031.geometry}
        material={nodes.Cylinder031.material}
        position={[-2.27, -0.38, -1.03]}
        rotation={[Math.PI / 2, 0, 1.55]}
        scale={[0.07, 0.05, 0.07]}
      />
    </group>
  )
}

useGLTF.preload('/MarsGallery.glb')
