import { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCylinder } from '@react-three/cannon'

useGLTF.preload('/test.glb')

// Auto-generated by: https://github.com/pmndrs/gltfjsx
const Wheel = forwardRef(({ radius = 0.7, leftSide, pos,posz,...props }, ref) => {
  const { nodes, materials } = useGLTF('/test.glb')
  useCylinder(() => ({ mass: 1, type: 'Kinematic', material: 'wheel', collisionFilterGroup: 0, args: [radius, radius, 0.5, 16], ...props }), ref)
  return (
    <mesh ref={ref}>
       <group scale={[-1, -1, -1]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft001.geometry} material={materials.carTire} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft001_1.geometry} material={materials['_defaultMat.003']} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft001_2.geometry} material={materials.plastic} />
      </group>
    </mesh>
  )
})

export default Wheel
